image: golang:1.18

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - go build ./...

unit-test-job:
  stage: test
  script:
    - go test -v -race ./...

lint-test-job:
  stage: test
  script:
    - go vet ./...